# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 20:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerCourse',
            fields=[
            ],
            options={
                'verbose_name': '轮播课程',
                'indexes': [],
                'proxy': True,
                'verbose_name_plural': '轮播课程',
            },
            bases=('courses.course',),
        ),
    ]
